// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.2 and Filter Design HDL Coder 24.2.
// Generated on: 2024-11-30 17:08:47
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// LoopUnrolling: on

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Multipliers           : 11



`timescale 1 ns / 1 ns

module fi
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [7:0] filter_in; //sfix8_En15
  output  signed [23:0] filter_out; //sfix24_En30

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b0000000010100110; //sfix16_En15
  parameter signed [15:0] coeff2 = 16'b1111111001100010; //sfix16_En15
  parameter signed [15:0] coeff3 = 16'b0000010001011010; //sfix16_En15
  parameter signed [15:0] coeff4 = 16'b1111011111011111; //sfix16_En15
  parameter signed [15:0] coeff5 = 16'b0000101101101110; //sfix16_En15
  parameter signed [15:0] coeff6 = 16'b0111001010100011; //sfix16_En15
  parameter signed [15:0] coeff7 = 16'b0000101101101110; //sfix16_En15
  parameter signed [15:0] coeff8 = 16'b1111011111011111; //sfix16_En15
  parameter signed [15:0] coeff9 = 16'b0000010001011010; //sfix16_En15
  parameter signed [15:0] coeff10 = 16'b1111111001100010; //sfix16_En15
  parameter signed [15:0] coeff11 = 16'b0000000010100110; //sfix16_En15

  // Signals
  reg  signed [7:0] delay_pipeline [0:10] ; // sfix8_En15
  wire signed [22:0] product11; // sfix23_En30
  wire signed [23:0] mul_temp; // sfix24_En30
  wire signed [22:0] product10; // sfix23_En30
  wire signed [23:0] mul_temp_1; // sfix24_En30
  wire signed [22:0] product9; // sfix23_En30
  wire signed [23:0] mul_temp_2; // sfix24_En30
  wire signed [22:0] product8; // sfix23_En30
  wire signed [23:0] mul_temp_3; // sfix24_En30
  wire signed [22:0] product7; // sfix23_En30
  wire signed [23:0] mul_temp_4; // sfix24_En30
  wire signed [22:0] product6; // sfix23_En30
  wire signed [23:0] mul_temp_5; // sfix24_En30
  wire signed [22:0] product5; // sfix23_En30
  wire signed [23:0] mul_temp_6; // sfix24_En30
  wire signed [22:0] product4; // sfix23_En30
  wire signed [23:0] mul_temp_7; // sfix24_En30
  wire signed [22:0] product3; // sfix23_En30
  wire signed [23:0] mul_temp_8; // sfix24_En30
  wire signed [22:0] product2; // sfix23_En30
  wire signed [23:0] mul_temp_9; // sfix24_En30
  wire signed [23:0] product1_cast; // sfix24_En30
  wire signed [22:0] product1; // sfix23_En30
  wire signed [23:0] mul_temp_10; // sfix24_En30
  wire signed [23:0] sum1; // sfix24_En30
  wire signed [23:0] add_signext; // sfix24_En30
  wire signed [23:0] add_signext_1; // sfix24_En30
  wire signed [24:0] add_temp; // sfix25_En30
  wire signed [23:0] sum2; // sfix24_En30
  wire signed [23:0] add_signext_2; // sfix24_En30
  wire signed [23:0] add_signext_3; // sfix24_En30
  wire signed [24:0] add_temp_1; // sfix25_En30
  wire signed [23:0] sum3; // sfix24_En30
  wire signed [23:0] add_signext_4; // sfix24_En30
  wire signed [23:0] add_signext_5; // sfix24_En30
  wire signed [24:0] add_temp_2; // sfix25_En30
  wire signed [23:0] sum4; // sfix24_En30
  wire signed [23:0] add_signext_6; // sfix24_En30
  wire signed [23:0] add_signext_7; // sfix24_En30
  wire signed [24:0] add_temp_3; // sfix25_En30
  wire signed [23:0] sum5; // sfix24_En30
  wire signed [23:0] add_signext_8; // sfix24_En30
  wire signed [23:0] add_signext_9; // sfix24_En30
  wire signed [24:0] add_temp_4; // sfix25_En30
  wire signed [23:0] sum6; // sfix24_En30
  wire signed [23:0] add_signext_10; // sfix24_En30
  wire signed [23:0] add_signext_11; // sfix24_En30
  wire signed [24:0] add_temp_5; // sfix25_En30
  wire signed [23:0] sum7; // sfix24_En30
  wire signed [23:0] add_signext_12; // sfix24_En30
  wire signed [23:0] add_signext_13; // sfix24_En30
  wire signed [24:0] add_temp_6; // sfix25_En30
  wire signed [23:0] sum8; // sfix24_En30
  wire signed [23:0] add_signext_14; // sfix24_En30
  wire signed [23:0] add_signext_15; // sfix24_En30
  wire signed [24:0] add_temp_7; // sfix25_En30
  wire signed [23:0] sum9; // sfix24_En30
  wire signed [23:0] add_signext_16; // sfix24_En30
  wire signed [23:0] add_signext_17; // sfix24_En30
  wire signed [24:0] add_temp_8; // sfix25_En30
  wire signed [23:0] sum10; // sfix24_En30
  wire signed [23:0] add_signext_18; // sfix24_En30
  wire signed [23:0] add_signext_19; // sfix24_En30
  wire signed [24:0] add_temp_9; // sfix25_En30
  reg  signed [23:0] output_register; // sfix24_En30

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[10] * coeff11;
  assign product11 = mul_temp[22:0];

  assign mul_temp_1 = delay_pipeline[9] * coeff10;
  assign product10 = mul_temp_1[22:0];

  assign mul_temp_2 = delay_pipeline[8] * coeff9;
  assign product9 = mul_temp_2[22:0];

  assign mul_temp_3 = delay_pipeline[7] * coeff8;
  assign product8 = mul_temp_3[22:0];

  assign mul_temp_4 = delay_pipeline[6] * coeff7;
  assign product7 = mul_temp_4[22:0];

  assign mul_temp_5 = delay_pipeline[5] * coeff6;
  assign product6 = mul_temp_5[22:0];

  assign mul_temp_6 = delay_pipeline[4] * coeff5;
  assign product5 = mul_temp_6[22:0];

  assign mul_temp_7 = delay_pipeline[3] * coeff4;
  assign product4 = mul_temp_7[22:0];

  assign mul_temp_8 = delay_pipeline[2] * coeff3;
  assign product3 = mul_temp_8[22:0];

  assign mul_temp_9 = delay_pipeline[1] * coeff2;
  assign product2 = mul_temp_9[22:0];

  assign product1_cast = $signed({{1{product1[22]}}, product1});

  assign mul_temp_10 = delay_pipeline[0] * coeff1;
  assign product1 = mul_temp_10[22:0];

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{1{product2[22]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[23:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{1{product3[22]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[23:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{1{product4[22]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[23:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{1{product5[22]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[23:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{1{product6[22]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[23:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{1{product7[22]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[23:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{1{product8[22]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[23:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{1{product9[22]}}, product9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[23:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{1{product10[22]}}, product10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[23:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{1{product11[22]}}, product11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[23:0];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum10;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
